---
all:
  hosts:
    master01:
      ansible_host: 'xx.xx.xx.xx'
      ansible_user: 'root'
      ansible_ssh_pass: 'xxxxx'
      ha_role: ha_master
      NIC: ensxxx
    master02:
      ansible_host: 'xx.xx.xx.xx'
      ansible_user: 'root'
      ansible_ssh_pass: 'xxxxx'
      ha_role: ha_backup
      NIC: ensxxx
    master03:
      ansible_host: 'xx.xx.xx.xx'
      ansible_user: 'root'
      ansible_ssh_pass: 'xxxxx'
      ha_role: ha_backup
      NIC: ensxxx
  children:
    master_nodes:
      hosts:
        master01:
        master02:
        master03:
    worker_nodes:
      hosts:

