---
- name: configure the yum repository of kubernetes
  yum_repository:
    name: kubernetes
    description: kubernetes yum repo
    baseurl: http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - http://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
      - http://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

- name: install kubelet, kubeadm and kubectl
  package:
    name:
      - "kubelet-{{ k8s_version }}"
      - "kubeadm-{{ k8s_version }}"
      - "kubectl-{{ k8s_version }}"
    state: present

- name: restart kubelet service
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: configure auto-completation for k8s
  lineinfile:
    dest: ~/.bashrc
    line: "source <(kubectl completion bash)"

- name: pull docker image for master
  docker_image:
    name: "{{ k8s_aliyun_url }}/{{ item }}"
    source: pull
  with_items:
    - k8s_api:v{{ k8s_version }}
    - k8s_controller:v{{ k8s_version }}
    - k8s_scheduler:v{{ k8s_version }}
    - k8s_etcd
    - k8s_proxy:v{{ k8s_version }}
    - k8s_pause
    - k8s_coredns

- name: re-tag the docker image
  docker_image:
    name: "{{ k8s_aliyun_url }}/{{ item }}"
    repository: "{{ k8s_gcr_url }}/{{ item }}"
    push: no
    source: local
  with_items:
    - k8s_api:v{{ k8s_version }}
    - k8s_controller:v{{ k8s_version }}
    - k8s_scheduler:v{{ k8s_version }}
    - k8s_etcd
    - k8s_proxy:v{{ k8s_version }}
    - k8s_pause
    - k8s_coredns

- name: remove the docker image with aliyun tag
  docker_image:
    name: "{{ k8s_aliyun_url }}/{{ item }}"
    state: absent
  with_items:
    - k8s_api:v{{ k8s_version }}
    - k8s_controller:v{{ k8s_version }}
    - k8s_scheduler:v{{ k8s_version }}
    - k8s_etcd
    - k8s_proxy:v{{ k8s_version }}
    - k8s_pause
    - k8s_coredns