---
- name: configure the yum repository of kubernetes
  yum_repository:
    name: kubernetes
    description: kubernetes yum repo
    baseurl: http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no  # should be no, check failed
    repo_gpgcheck: no # should be no, check failed
    gpgkey:
      - http://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
      - http://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

- name: install kubelet, kubeadm and kubectl
  package:
    name:
      - "kubelet-{{ k8s_version }}"
      - "kubeadm-{{ k8s_version }}"
      - "kubectl-{{ k8s_version }}"
    state: present

- name: restart kubelet service
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
