---
- name: replace the base repo with aliyun one
  get_url:
    url: "{{ aliyun_base_repo }}"
    dest: /etc/yum.repos.d/CentOS-Base.repo
    force: yes

- name: install aliyun epel repository
  yum:
    name: "{{ aliyun_epel_repo }}"
    state: present
    update_cache: yes
