---
- name: install or update packages
  package:
    name:
      - ntp
      - ntpdate
      - rsync
      - bash-completion
      - net-tools
      - wget
      - gcc
      - gcc-c++
      - lrzsz
      - vim
      - unzip
      - make
      - openssl-devel
      - openssh
      - iptables-services
      - python-docker
      - iscsi-initiator-utils
      - ipvsadm
    state: latest

- name: start and enable iscsi daemon
  systemd:
    name: iscsid
    state: started
    enabled: yes