---
- name: NTP - delete NTP configration
  lineinfile:
    dest: /etc/ntp.conf
    regexp: "^server"
    state: absent

- name: NTP - delete ntpdate configration
  lineinfile:
    dest: /etc/ntp/step-tickers
    regexp: "^0"
    state: absent

- name: NTP - add NTP server
  lineinfile:
    dest: /etc/ntp.conf
    line: "{{ item }}"
  with_items:
    - "server ntp.aliyun.com"
    - "server ntp1.aliyun.com"

- name: NTP - add ntpdate configration
  lineinfile:
    dest: /etc/ntp/step-tickers
    line: "ntp1.aliyun.com"

- name: NTP - start ntpd
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: NTP - Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai
