---
- name: copy ipvs.modules file into host
  copy:
    src: ipvs.modules
    dest: /etc/sysconfig/modules/ipvs.modules
    owner: root
    group: root
    mode: 0755

- name: enable ipvs config
  command: bash /etc/sysconfig/modules/ipvs.modules
